# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.timezone)),
                ('update_date', models.DateField()),
            ],
        ),
    ]
